source "https://rubygems.org"

gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "rack", "~> 1.6.11" # added on advice of github
gem "rack-protection", "~> 1.5.5" # added on advice of github
gem 'pg'

ruby '2.4.1'

group :production do
  gem 'puma'
end